apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-secret
spec:
  selector:
    matchLabels:
      app: node-secret
  template:
    metadata:
      labels:
        app: node-secret
    spec:
      volumes:
      - name: secrets
        secret:
          secretName: demo-secret
      containers:
      - env:
        - name: password2
          valueFrom:
            secretKeyRef:
              name: demo-secret
              key: password2

        image: edwinguo123/secret-demo:latest
        name: secret-demo
        imagePullPolicy: Always 
        ports:
        - containerPort: 9000

        # Reference secret data at appropriate path (/etc/config)
        volumeMounts:
        - name: secrets 
          mountPath: /etc/config
          readOnly: true

