apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deploy
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec: 
      containers:
      - name: hello-pod
        image: edwinguo123/wcd_js_class_demo:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

