apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
      track: canary
  template:
    metadata:
      labels:
        app: web 
        track: canary
    spec:
      containers:
      - name: hello-pod
        image: edwinguo123/wcd_js_class_demo:v2  
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
